//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinBartos.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MartinBartos.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File scoped namespace and type declaration should have empty line between..
        /// </summary>
        internal static string FileScopedNamespaceAnalyzerDescription {
            get {
                return ResourceManager.GetString("FileScopedNamespaceAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty line between namespace and type declaration.
        /// </summary>
        internal static string FileScopedNamespaceAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("FileScopedNamespaceAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty line between namespace and type declaration.
        /// </summary>
        internal static string FileScopedNamespaceAnalyzerTitle {
            get {
                return ResourceManager.GetString("FileScopedNamespaceAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple empty lines are not allowed.
        /// </summary>
        internal static string MultipleLinesAnalyzerDescription {
            get {
                return ResourceManager.GetString("MultipleLinesAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicit empty line.
        /// </summary>
        internal static string MultipleLinesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MultipleLinesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicit empty line.
        /// </summary>
        internal static string MultipleLinesAnalyzerTitle {
            get {
                return ResourceManager.GetString("MultipleLinesAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After if keyword should be space.
        /// </summary>
        internal static string WrongIfFormatAnalyzerDescription {
            get {
                return ResourceManager.GetString("WrongIfFormatAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space missing after if keyword.
        /// </summary>
        internal static string WrongIfFormatAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("WrongIfFormatAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space missing after if keyword.
        /// </summary>
        internal static string WrongIfFormatAnalyzerTitle {
            get {
                return ResourceManager.GetString("WrongIfFormatAnalyzerTitle", resourceCulture);
            }
        }
    }
}
